# Generated by Django 3.2 on 2024-03-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100, verbose_name='图片名字')),
                ('face_status', models.CharField(default='', max_length=100, verbose_name='表情')),
                ('status', models.BooleanField(default=False, verbose_name='是否存在危险')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'pic',
            },
        ),
    ]
